import React, { useState } from "react";
import Head from "next/head";
import Script from "next/script";
import {
    Container, Row, Col, Button
} from "react-bootstrap";
import styles from "../styles/Home.module.scss";
import {
    NavBar,
    TabMenu,
    Input,
    SelectInput,
    HorizontalInput,
    HorizontalSelect,
    TextareaInput,
    CheckBox
} from "../components";

const optionsLanguage = [
    "Singapore",
    "Vietnam"
];

const optionsGender = [
    "Male",
    "Female"
];

export default function Home() {
    const [activeIndex, setActiveIndex] = useState<number>(1);
    const [checked, setChecked] = useState<boolean>(false);

    return (
        <Container fluid className={styles.container}>
            <Script src="/static/js/toggle-dropdown.js" />
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <Container className={styles.container__content}>
                <TabMenu activeIndex={activeIndex} onChangeTabMenu={(index) => setActiveIndex(index)} />
                <Row className={styles.profile}>
                    <Col lg={6} className={`px-0 ${styles["profile__left"]}`}>
                        <div className={styles["profile__content"]}>
                            <img
                                src="/static/images/image.png"
                                width="145"
                                height="145"
                            />
                            <div className={styles["profile__name"]}>
                                Howdycandidate
                            </div>
                            <div className={styles["profile__thb"]}>
                                THB 565.000
                            </div>
                        </div>
                        <div className={styles["communication-details"]}>
                            <div className={styles.title}>Communication Details</div>
                            <Input
                                title="Mobile Number"
                                value="*********98765"
                                actionText="Verify"
                                className="mb-2"
                            />
                            <SelectInput
                                value="Singapore"
                                options={optionsLanguage}
                                title="Language"
                            />
                        </div>
                    </Col>
                    <Col lg={6} className={`px-0 ${styles["account-details"]}`}>
                        <div className={styles.title}>Account Details</div>
                        <HorizontalInput
                            title="Username"
                            value="howdycandidate"
                            hasBackground
                            hasPadLock
                            actionText=""
                            className="mb-2 mt-2"
                            inputType="text"
                        />
                        <HorizontalInput
                            title="First Name"
                            value="howdycandidate"
                            hasBackground={false}
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="text"
                        />
                        <HorizontalInput
                            title="Date of Birth"
                            value="1999-10-12"
                            hasBackground
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="date"
                        />
                        <HorizontalInput
                            title="Password"
                            value=""
                            hasBackground={false}
                            hasPadLock={false}
                            actionText="Change Password"
                            className="mb-2"
                            inputType=""
                        />
                        <HorizontalInput
                            title="Country"
                            value="Chile"
                            hasBackground
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="text"
                        />
                        <HorizontalInput
                            title="Currency"
                            value="THB"
                            hasBackground={false}
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="text"
                        />
                        <HorizontalInput
                            title="Last Name"
                            value="pewpew"
                            hasBackground
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="text"
                        />
                        <HorizontalInput
                            title="Email"
                            value="email@example.com"
                            hasBackground={false}
                            hasPadLock
                            actionText=""
                            className="mb-2"
                            inputType="email"
                        />
                        <HorizontalSelect
                            title="Gender"
                            value="Male"
                            options={optionsGender}
                            hasBackground
                            className=""
                        />
                    </Col>
                    <Col lg={12} className="px-0">
                        <Row className={`${styles.address} mx-0`}>
                            <div className={styles.col__left}>
                                <div className={styles.title}>Home Address</div>
                                <TextareaInput
                                    title="Address"
                                    value="Address"
                                    rows={3}
                                />
                            </div>
                            <div className={styles.col__left}>
                                <Input
                                    title="Town/City"
                                    value="Town/City"
                                    actionText=""
                                    className="mb-3"
                                />
                                <Input
                                    title="Postal Code"
                                    value="00000"
                                    actionText=""
                                    className=""
                                />
                            </div>
                        </Row>
                    </Col>

                    <Col lg={12}>
                        <Container fluid className={`${styles.footer} px-0`}>
                            <div className={styles["footer__question"]}>
                                Would you like to get the latest promos, updates, and offers?
                            </div>
                            <div className={styles["footer__accept"]}>
                                <CheckBox
                                    checked={checked}
                                    onChange={(e) => setChecked(e.target.checked)}
                                />
                                <div className={styles.message__accept}>
                                    Yes. Send me the latest promotions, updates and offers.
                                </div>
                            </div>
                            <div className={styles["footer__button"]}>
                                <Button
                                    className={styles["btn__save-change"]}
                                >
                                    Save Change
                                </Button>
                                <Button
                                    className={styles["btn__cancel"]}
                                >
                                    Cancel
                                </Button>
                            </div>
                        </Container>
                    </Col>
                </Row>
            </Container>
        </Container>
    )
}
